import { createClient } from '@urql/core';
import { Component, createResource, createSignal, For } from 'solid-js';
// Generated by https://quicktype.io

export interface Todo {
  id: string;
  done: boolean;
  text: string;
}

const client = createClient({
  url: "http://0.0.0.0:4000/graphql"
})

const [todos] = createResource<Todo[]>(() =>
  client.query(`
    query {
      getTodos{
        id
        done
        text
      }
    }`,
    {}
  )
    .toPromise()
    .then(({ data }) => data.getTodos)
)
console.log('🚀🚀🚀 ~ file: App.tsx ~ line 32 ~ todos', todos())

const App: Component = () => {
  const [text, setText] = createSignal('')
  const onAdd = ()=>{
    setText("")
  }
  return (
    <div>
      Todo:
      <For
        each={todos()}>
        {({ id, done, text }) => <div>
          <input type="checkbox" checked={done} />
          <span>{text}</span>
        </div>}
      </For>
      <div>{text()}</div>
      <div><input oninput={evt => setText(evt.currentTarget.value)} type="text" value={text()} />
      <button onclick={onAdd}>Add</button>
      </div>
    </div>
  );
};

export default App;
