import { createClient } from '@urql/core';
import { Component, createResource, createSignal, For } from 'solid-js';
// Generated by https://quicktype.io

export interface Todo {
  id: string;
  done: boolean;
  text: string;
}

const client = createClient({
  url: "http://0.0.0.0:4000/graphql"
})

const [todos, { refetch }] = createResource<Todo[]>(() =>
  client.query(`
    query {
      getTodos{
        id
        done
        text
      }
    }`,
    {}
  )
    .toPromise()
    .then(({ data }) => data.getTodos)
)

const App: Component = () => {
  const [text, setText] = createSignal('')
  const onAdd = async () => {
    await client.mutation(`
      mutation($text: String!) {
        addTodo(text: $text){
          id
        }
      }
    `, {
      text: text()
    })
      .toPromise()

    refetch()

    setText("")
  }

  const onToggle = async (id: string, done: boolean) => {
    client.mutation(`
      mutation($id: ID!, $done: Boolean!){
        setDone(id: $id, done: $done){
          id
          text
        }
      }
    `, {
        id,
        done
    })
    .toPromise()

    refetch()
  }

  return (
    <div>
      Todo:
      <For
        each={todos()}>
        {({ id, done, text }) => <div>
          <input type="checkbox" checked={done} onclick={() => onToggle(id, !done)} />
          <span>{text}</span>
        </div>}
      </For>
      <div>
        <input oninput={evt => setText(evt.currentTarget.value)} type="text" value={text()} />
        <button onclick={onAdd}>Add</button>
      </div>
    </div>
  );
};

export default App;
